apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
  label: javaapp
spec:
  selector:
    app: javaapp  # Should match the label in your Deployment
  ports:
    - nodeport: 30036
      port: 80  # The port you want to expose the service on
      targetPort: 8001  # The port your Java application listens on inside the container
  type: LoadBalancer  # Expose the service using an AWS LoadBalancer
